(in-package :star.event-store)

(setf (documentation 'event-store-error 'type)
      "Base condition for canonical event-store failures.")
(setf (documentation 'event-store-conflict 'type)
      "Signals reuse of an immutable event id with different logical content.")
(setf (documentation 'event-store-version-conflict 'type)
      "Signals a failed expected stream sequence or predecessor check.")
(setf (documentation 'event-store-gap 'type)
      "Signals an incomplete or discontinuous event stream during replay.")

(setf (documentation 'event-store-conflict-event-id 'function)
      "Event id whose immutable content conflicted.")
(setf (documentation 'event-store-version-conflict-stream-id 'function)
      "Stream whose optimistic version check failed.")
(setf (documentation 'event-store-version-conflict-expected 'function)
      "Expected sequence or predecessor supplied by the caller.")
(setf (documentation 'event-store-version-conflict-actual 'function)
      "Actual sequence or predecessor observed at the stream head.")
(setf (documentation 'event-store-gap-stream-id 'function)
      "Stream whose replay continuity check failed.")
(setf (documentation 'event-store-gap-expected-sequence 'function)
      "Sequence expected next during replay.")
(setf (documentation 'event-store-gap-actual-sequence 'function)
      "Sequence actually observed during replay, or NIL when missing.")

(setf (documentation 'event-store-record 'type)
      "Immutable canonical event-source record.")
(setf (documentation 'event-store-record-event-id 'function)
      "Globally idempotent event id of an event-store record.")
(setf (documentation 'event-store-record-stream-id 'function)
      "Logical ordered stream containing an event-store record.")
(setf (documentation 'event-store-record-sequence 'function)
      "Zero-based sequence of an event within its stream.")
(setf (documentation 'event-store-record-predecessor-id 'function)
      "Previous event id in the stream, or NIL for sequence zero.")
(setf (documentation 'event-store-record-event-type 'function)
      "Stable event type string recorded for replay dispatch.")
(setf (documentation 'event-store-record-payload 'function)
      "Exact canonical payload string retained by the event source.")
(setf (documentation 'event-store-record-payload-digest 'function)
      "SHA-256 digest of the retained payload bytes.")
(setf (documentation 'event-store-record-recorded-at 'function)
      "Source timestamp retained with the event record.")
(setf (documentation 'event-store-record-metadata 'function)
      "Owned metadata snapshot retained with the event record.")

(setf (documentation 'event-store-append-result 'type)
      "Result of an idempotent event-store append.")
(setf (documentation 'make-event-store-append-result 'function)
      "Construct an event-store append result.")
(setf (documentation 'event-store-append-result-status 'function)
      "Append status, currently :APPENDED or :REPLAYED.")
(setf (documentation 'event-store-append-result-event-id 'function)
      "Event id accepted by the append operation.")
(setf (documentation 'event-store-append-result-stream-id 'function)
      "Stream id containing the accepted event.")
(setf (documentation 'event-store-append-result-sequence 'function)
      "Assigned or previously assigned stream sequence.")
(setf (documentation 'event-store-append-result-payload-digest 'function)
      "SHA-256 digest of the accepted payload bytes.")

(setf (documentation 'event-store-open-p 'function)
      "Return true when the supplied Tek9 event store is open.")
