(uiop:define-package :star.event-store
  (:use :cl)
  (:documentation
   "Append-only Tek9 event source used for deterministic StarIntel replay.")
  (:export
   #:*event-store*
   #:*event-store-name*
   #:*event-store-path*
   #:event-store-error
   #:event-store-conflict
   #:event-store-conflict-event-id
   #:event-store-version-conflict
   #:event-store-version-conflict-stream-id
   #:event-store-version-conflict-expected
   #:event-store-version-conflict-actual
   #:event-store-gap
   #:event-store-gap-stream-id
   #:event-store-gap-expected-sequence
   #:event-store-gap-actual-sequence
   #:event-store-record
   #:event-store-record-event-id
   #:event-store-record-stream-id
   #:event-store-record-sequence
   #:event-store-record-predecessor-id
   #:event-store-record-event-type
   #:event-store-record-payload
   #:event-store-record-payload-digest
   #:event-store-record-recorded-at
   #:event-store-record-metadata
   #:event-store-append-result
   #:make-event-store-append-result
   #:event-store-append-result-status
   #:event-store-append-result-event-id
   #:event-store-append-result-stream-id
   #:event-store-append-result-sequence
   #:event-store-append-result-payload-digest
   #:open-event-store
   #:close-event-store
   #:event-store-open-p
   #:append-event
   #:fetch-event
   #:event-store-stream-head
   #:event-store-record-at-sequence
   #:replay-event-stream
   #:verify-event-stream))
