(uiop:define-package   :star.consumers
  (:use       :cl #:LPARALLEL)
  (:documentation "doc")
  (:export
   #:consumer
   #:consumer-name
   #:consumer-filter
   #:consumer-fn
   #:consumer-take
   #:consumer-queue
   #:consumer-channel
   #:consumer-max-size
   #:consumer-state
   #:consumer-stream
   #:consumer-lock
   #:consumer-update-state
   #:consumer-cleanup
   #:with-consumer-lock
   #:consumer-update
   #:consumer-read
   #:consume
   #:start-consumer
   #:make-consumer
   #:rabbit-queue-stream
   #:rabbit-stream-exchange
   #:rabbit-exchange-type
   #:rabbit-exchange-durable-p
   #:rabbit-stream-routing-key
   #:rabbit-stream-user
   #:rabbit-stream-password
   #:rabbit-stream-vhost
   #:rabbit-stream-port
   #:rabbit-stream-host
   #:rabbit-stream-queue-durable-p
   #:rabbit-stream-queue-name
   #:rabbit-stream-connection
   #:rabbit-stream-channel
   #:rabbit-stream-open-p
   #:open-stream
   #:close-stream
   #:stream-read
   #:rabbit-consumer
   #:create-rabbit-consumer))
