(uiop:define-package :star.leases
  (:use :cl)
  (:export
   #:+lease-record-version+
   #:lease-identity
   #:make-lease-identity
   #:lease-identity-tenant-id
   #:lease-identity-program-id
   #:lease-identity-target-namespace
   #:lease-identity-target-id
   #:lease-identity-actor-name
   #:lease-identity-workflow-name
   #:lease-identity-operation-class
   #:canonical-target-lock-key
   #:lease-record
   #:make-lease-record
   #:lease-record-lock-key
   #:lease-record-identity
   #:lease-record-lease-id
   #:lease-record-owner-principal-id
   #:lease-record-owner-client-id
   #:lease-record-owner-credential-id
   #:lease-record-service-instance-id
   #:lease-record-fencing-token
   #:lease-record-acquired-at
   #:lease-record-renewed-at
   #:lease-record-expires-at
   #:lease-record-ttl-ms
   #:lease-record-maximum-lifetime-ms
   #:lease-record-execution-id
   #:lease-record-job-id
   #:lease-record-trace-id
   #:lease-record-request-id
   #:lease-record-metadata
   #:lease-record-state
   #:serialize-lease-record
   #:deserialize-lease-record
   #:lease-outcome
   #:make-lease-outcome
   #:+lease-outcome-codes+
   #:lease-outcome-code
   #:lease-outcome-lease
   #:lease-outcome-leases
   #:lease-outcome-retryable-p
   #:lease-outcome-detail
   #:+retryable-lease-outcome-codes+
   #:retryable-lease-outcome-code-p
   #:+lease-identifier-max-bytes+
   #:+lease-reason-max-bytes+
   #:+lease-metadata-max-bytes+
   #:+lease-metadata-max-keys+
   #:utf-8-byte-length
   #:valid-lease-identifier-p
   #:valid-lease-reason-p
   #:lease-metadata-object-p
   #:valid-lease-metadata-p
   #:valid-lease-filter-p
   #:valid-lease-component-filter-p
   #:lease-store
   #:memory-lease-store
   #:make-memory-lease-store
   #:valkey-lease-store
   #:make-valkey-lease-store
   #:acquire-lease
   #:renew-lease
   #:release-lease
   #:get-lease
   #:list-leases
   #:revoke-lease
   #:backend-health
   #:close-lease-store
   #:lease-runtime
   #:make-lease-runtime
   #:lease-runtime-store
   #:lease-runtime-closed-p
   #:close-lease-runtime))
