(in-package :star.storage)

(setf (documentation 'storage-backend-name 'function)
      "Return the registry name of a storage backend.")
(setf (documentation 'memory-storage-backend 'type)
      "In-memory implementation of the document storage protocol for tests and local use.")
(setf (documentation 'make-memory-storage-backend 'function)
      "Create an in-memory storage backend named NAME.")
(setf (documentation 'resolve-storage-backend 'function)
      "Resolve a registered storage backend by NAME, optionally returning NIL when absent.")
(setf (documentation 'storage-backend-error 'type)
      "Condition describing a failed storage backend operation.")
(setf (documentation 'storage-backend-error-backend 'function)
      "Return the backend name associated with a storage backend error.")
(setf (documentation 'storage-backend-error-operation 'function)
      "Return the operation associated with a storage backend error.")
(setf (documentation 'storage-backend-error-key 'function)
      "Return the object key associated with a storage backend error.")
(setf (documentation 'storage-backend-error-reason 'function)
      "Return the diagnostic reason associated with a storage backend error.")
(setf (documentation 'valid-storage-tier-p 'function)
      "Return true when TIER names one of the supported logical document tiers.")
(setf (documentation 'normalize-storage-tier 'function)
      "Normalize and validate TIER, signalling an error for unsupported tiers.")
(setf (documentation 'document-storage-tier 'function)
      "Return DOCUMENT's explicit storage tier or the implicit hot tier.")
(setf (documentation 'document-storage-backend-name 'function)
      "Return the server-selected backend name recorded for DOCUMENT.")
(setf (documentation 'document-storage-object-key 'function)
      "Return DOCUMENT's external object key, or NIL when the document is inline-only.")
