(uiop:define-package :star.storage
  (:use :cl)
  (:export
   #:+document-storage-extension-key+
   #:+document-storage-tiers+
   #:+file-ingest-extension-key+
   #:+file-storage-extension-key+
   #:storage-backend
   #:storage-backend-name
   #:memory-storage-backend
   #:make-memory-storage-backend
   #:register-storage-backend
   #:resolve-storage-backend
   #:configure-storage-backends
   #:storage-put
   #:storage-get
   #:storage-delete
   #:storage-head
   #:storage-backend-error
   #:storage-backend-error-backend
   #:storage-backend-error-operation
   #:storage-backend-error-key
   #:storage-backend-error-reason
   #:file-artifact-validation-error
   #:file-artifact-validation-reason
   #:prepare-file-artifact-document
   #:load-file-artifact
   #:file-artifact-json
   #:file-storage-metadata-object
   #:valid-storage-tier-p
   #:normalize-storage-tier
   #:tier-backend-name
   #:tenant-default-storage-tier
   #:document-storage-tier
   #:document-storage-backend-name
   #:document-storage-object-key
   #:document-storage-metadata
   #:document-storage-lifecycle-json
   #:storage-object-key
   #:load-document
   #:transition-document
   #:storage-aware-upsert-document
   #:delete-document-with-storage
   #:apply-document-storage-policy
   #:make-s3-storage-backend-from-settings))
