(in-package :star.api.client)

(defmethod initialize-instance :after ((client star-client) &key)
  "Preserve the historical MAKE-INSTANCE construction path used by star-cli."
  (unless (slot-boundp client 'base-url)
    (setf (slot-value client 'base-url) "http://127.0.0.1:5000"))
  (setf (slot-value client 'base-url)
        (normalize-base-url (slot-value client 'base-url)))
  (unless (slot-boundp client 'transport)
    (setf (slot-value client 'transport) (make-instance 'dexador-transport)))
  (unless (slot-boundp client 'authentication)
    (setf (slot-value client 'authentication)
          (make-instance 'anonymous-authentication)))
  (unless (slot-boundp client 'default-timeout-ms)
    (setf (slot-value client 'default-timeout-ms) 30000))
  (unless (slot-boundp client 'user-agent)
    (setf (slot-value client 'user-agent) "starintel-gserver-client/0.2"))
  (unless (slot-boundp client 'headers)
    (setf (slot-value client 'headers)
          '(("Accept" . "application/json"))))
  client)

(defmethod print-object ((result credential-secret-result) stream)
  (print-unreadable-object (result stream :type t :identity t)
    (write-string "api-key=REDACTED" stream)))
