logger {
  format = JSON
  output = Stdout
  level = info
}

config = [
  {
    node {
      name = clouseau
      domain = clouseau.starintel.internal
    }
    clouseau {
      dir = /var/lib/clouseau
      max_indexes_open = 100
      close_if_idle = true
      idle_check_interval_secs = 300
    }
    capacity {
      analyzer_exponent = 8
      cleanup_exponent = 8
      index_exponent = 10
      init_exponent = 10
      main_exponent = 8
    }
  }
]
