(in-package :star.actors)

(setf (documentation 'make-document-storage-command 'function)
      "Create a document-storage actor command envelope.")
(setf (documentation 'document-storage-command-operation 'function)
      "Return the requested document storage operation.")
(setf (documentation 'document-storage-command-document-id 'function)
      "Return the document id carried by a storage command.")
(setf (documentation 'document-storage-command-tier 'function)
      "Return the requested logical tier carried by a storage command.")
(setf (documentation 'document-storage-command-patch 'function)
      "Return the document patch carried by a storage upsert command.")
(setf (documentation 'document-storage-command-revision 'function)
      "Return the CouchDB revision carried by a storage delete command.")
(setf (documentation 'make-document-storage-result 'function)
      "Create a result envelope returned by the document-storage actor.")
(setf (documentation 'document-storage-result-status 'function)
      "Return the status keyword of a document storage result.")
(setf (documentation 'document-storage-result-operation 'function)
      "Return the operation represented by a document storage result.")
(setf (documentation 'document-storage-result-document-id 'function)
      "Return the document id represented by a document storage result.")
(setf (documentation 'document-storage-result-document 'function)
      "Return the hydrated canonical document carried by a storage result, when present.")
(setf (documentation 'document-storage-result-lifecycle 'function)
      "Return the lifecycle placement envelope carried by a storage result, when present.")
(setf (documentation 'document-storage-result-outcome 'function)
      "Return the optimistic document update outcome carried by a storage result, when present.")
(setf (documentation 'document-storage-result-error-code 'function)
      "Return the stable error code carried by a failed storage result.")
(setf (documentation 'document-storage-result-error-message 'function)
      "Return the diagnostic error message carried by a failed storage result.")
