(in-package :star.databases.couchdb)

(defparameter +exact-number-extension-key+ "_server_exact_numbers")
(defparameter +exact-number-max-tokens+ 4096)
(defparameter +exact-number-max-token-length+ 1048576)

(defun exact-storage-number-p (value)
  (or (starintel:json-number-p value) (floatp value)
      (and (integerp value) (> (abs value) 9007199254740991))))

(defun exact-storage-path-value (document path &optional (replacement nil replace-p))
  (unless (and (listp path) path (<= (length path) 128))
    (error "Invalid exact-number path"))
  (let ((current document))
    (loop for tail on path
          for part = (car tail)
          for final = (null (cdr tail))
          do (cond
               ((json-object-p current)
                (unless (and (stringp part) (outbox-object-has-key-p current part))
                  (error "Missing exact-number object path"))
                (if (and final replace-p)
                    (setf (jsown:val current part) replacement)
                    (setf current (jsown:val current part))))
               ((and (or (listp current) (vectorp current)) (not (stringp current)))
                (unless (and (integerp part) (<= 0 part) (< part (length current)))
                  (error "Missing exact-number array path"))
                (if (and final replace-p)
                    (setf (elt current part) replacement)
                    (setf current (elt current part))))
               (t (error "Exact-number path crosses a scalar"))))
    (if replace-p replacement current)))

(defun exact-storage-shape-hash (document paths)
  (let ((shape (star.documents:clone-json-value document)))
    (when (outbox-object-has-key-p shape "_rev") (jsown:remkey shape "_rev"))
    (dolist (path paths) (exact-storage-path-value shape path :null))
    (outbox-digest-string (star.actors::canonical-target-json shape))))

(defun exact-storage-binary64 (value)
  "Project a pinned-codec number once, using exact decimal parts and native rounding."
  (unless (starintel::json-numeric-p value) (error "Expected a JSON number"))
  (when (> (length (starintel:stringify-json value)) +exact-number-max-token-length+)
    (error "Exact-number token limit exceeded"))
  (multiple-value-bind (sign digits order) (starintel::json-decimal-parts value)
    (when (zerop sign) (return-from exact-storage-binary64 0.0d0))
    ;; Bound exponent expansion before arithmetic; no unsupported zero fallback.
    (unless (<= -323 order 309) (error "Unsupported CouchDB numeric projection"))
    (unless (<= (length digits) +exact-number-max-token-length+)
      (error "Exact-number coefficient limit exceeded"))
    (let* ((rational (* sign (parse-integer digits)
                        (expt 10 (- order (length digits)))))
           (projection (coerce rational 'double-float)))
      (unless (and (starintel::json-finite-float-p projection) (not (zerop projection)))
        (error "Unsupported CouchDB numeric projection"))
      projection)))

(defun exact-storage-number-matches-p (actual token)
  (let ((expected (starintel:parse-json token)))
    (unless (and (starintel::json-numeric-p actual)
                 (starintel::json-numeric-p expected))
      (return-from exact-storage-number-matches-p nil))
    ;; Reject unsupported projections before exact arithmetic on hostile tokens.
    ;; Binary64 equivalence verifies fidelity, not out-of-band tamper resistance.
    (handler-case
        (let* ((left (exact-storage-binary64 actual))
               (right (exact-storage-binary64 expected)))
          (and (starintel::json-finite-float-p left)
               (starintel::json-finite-float-p right)
               (= left right)))
      (error () nil))))

(defun prepare-exact-storage-document (document)
  "Attach bounded exact-token evidence atomically, without changing numeric fields."
  (let* ((copy (star.documents:clone-json-value document))
         (extensions-present (outbox-object-has-key-p copy "extensions"))
         (extensions (document-extensions copy))
         (records nil))
    ;; Caller data is never a source of server fidelity evidence.
    (when (outbox-object-has-key-p extensions +exact-number-extension-key+)
      (jsown:remkey extensions +exact-number-extension-key+))
    (labels ((walk (value path depth)
               (when (> depth 128) (error "Exact-number storage depth exceeded"))
               (cond
                 ((exact-storage-number-p value)
                  (when (>= (length records) +exact-number-max-tokens+)
                    (error "Exact-number storage token limit exceeded"))
                  (let ((token (jsown:to-json value)))
                    (when (> (length token) +exact-number-max-token-length+)
                      (error "Exact-number token limit exceeded"))
                    (unless (starintel::json-numeric-p (starintel:parse-json token))
                      (error "Invalid exact-number token"))
                    (unless (handler-case
                                (exact-storage-binary64 (starintel:parse-json token))
                              (error () nil))
                      (error "Exact number has no supported finite CouchDB projection"))
                    (push (jsown:new-js ("path" (coerce path 'vector)) ("token" token)) records)))
                 ((json-object-p value)
                  (jsown:do-json-keys (key child) value
                    (walk child (append path (list key)) (1+ depth))))
                 ((and (or (listp value) (vectorp value)) (not (stringp value)))
                  (loop for child across (coerce value 'vector)
                        for index from 0 do (walk child (append path (list index)) (1+ depth)))))))
      (walk copy nil 0))
    (when records
      (setf records (nreverse records))
      (let ((paths (mapcar (lambda (record) (coerce (jsown:val record "path") 'list)) records)))
        (setf (jsown:val extensions +exact-number-extension-key+)
              (jsown:new-js
                ("version" 1)
                ("extensions_present" (if extensions-present :true :false))
                ("shape_hash" (exact-storage-shape-hash copy paths))
                ("tokens" (coerce records 'vector)))
              (jsown:val copy "extensions") extensions)))
    copy))

(defun restore-exact-storage-document (document)
  "Verify and restore exact tokens from complete stored documents, never ingress."
  (let* ((extensions (document-extensions document))
         (evidence (outbox-object-value extensions +exact-number-extension-key+)))
    (unless (outbox-object-has-key-p extensions +exact-number-extension-key+)
      (return-from restore-exact-storage-document document))
    (unless (and (json-object-p evidence)
                 (eql 1 (outbox-object-value evidence "version"))
                 (member (outbox-object-value evidence "extensions_present") '(:true :false))
                 (stringp (outbox-object-value evidence "shape_hash")))
      (error "Malformed exact-number evidence"))
    (let* ((copy (star.documents:clone-json-value document))
           (copy-extensions (document-extensions copy))
           (records (sequence-list (outbox-object-value evidence "tokens")))
           (paths nil))
      (unless (and records (<= (length records) +exact-number-max-tokens+))
        (error "Invalid exact-number evidence count"))
      (jsown:remkey copy-extensions +exact-number-extension-key+)
      (when (and (eq :false (jsown:val evidence "extensions_present"))
                 (null (cdr copy-extensions)))
        (jsown:remkey copy "extensions"))
      (dolist (record records)
        (unless (and (json-object-p record) (stringp (outbox-object-value record "token")))
          (error "Malformed exact-number record"))
        (let* ((path (sequence-list (outbox-object-value record "path")))
               (token (jsown:val record "token"))
               (actual (exact-storage-path-value copy path)))
          (when (or (member path paths :test #'equal) (> (length token) +exact-number-max-token-length+))
            (error "Duplicate or oversized exact-number record"))
          (unless (exact-storage-number-matches-p actual token)
            (error "Stale exact-number evidence"))
          (push path paths)))
      (unless (string= (jsown:val evidence "shape_hash")
                       (exact-storage-shape-hash copy paths))
        (error "Exact-number evidence does not match stored content"))
      (dolist (record records)
        (exact-storage-path-value
         copy (sequence-list (jsown:val record "path"))
         (star.documents:native-json-to-document
          (starintel:parse-json (jsown:val record "token")))))
      copy)))
