(uiop:define-package :star.databases.runtime
  (:use :cl)
  (:import-from :bordeaux-threads
                #:make-lock
                #:with-lock-held)
  (:import-from :sento.actor
                #:*sender*
                #:reply)
  (:import-from :sento.actor-context
                #:actor-of)
  (:export
   #:database-runtime-error
   #:database-runtime-error-code
   #:database-runtime-error-retryable-p
   #:database-runtime-error-details
   #:database-backend
   #:database-backend-id
   #:database-backend-health
   #:database-execute-read
   #:database-execute-write
   #:database-execute-transaction
   #:database-subscribe
   #:database-cancel-subscription
   #:database-close
   #:database-profile
   #:database-profile-name
   #:database-profile-backend-id
   #:database-profile-options
   #:database-operation
   #:database-operation-name
   #:database-operation-profile
   #:database-operation-access
   #:database-operation-descriptor
   #:database-operation-result-limit
   #:database-operation-timeout-ms
   #:database-call-context
   #:make-database-call-context
   #:database-call-context-principal
   #:database-call-context-tenant-id
   #:database-call-context-dataset-id
   #:database-call-context-correlation-id
   #:database-call-context-deadline
   #:database-request
   #:make-database-request
   #:database-request-operation
   #:database-request-bindings
   #:database-request-context
   #:database-request-idempotency-key
   #:database-request-precondition
   #:database-result
   #:database-result-status
   #:database-result-operation
   #:database-result-value
   #:database-result-error-code
   #:database-result-retryable-p
   #:database-result-details
   #:register-database-backend
   #:unregister-database-backend
   #:find-database-backend
   #:register-database-profile
   #:unregister-database-profile
   #:find-database-profile
   #:register-database-operation
   #:unregister-database-operation
   #:find-database-operation
   #:clear-database-runtime
   #:execute-database-request
   #:database-runtime-command
   #:make-database-runtime-command
   #:database-runtime-command-request
   #:make-database-runtime-handler
   #:start-database-runtime-actor
   #:fake-database-backend
   #:make-fake-database-backend
   #:fake-database-backend-calls))
