(uiop:define-package :star.playbook
  (:use :cl)
  (:documentation
   "Tenant-scoped StarIntel playbooks compiled to LISA production rules.")
  (:export
   #:playbook-error
   #:playbook-error-code
   #:playbook-error-message
   #:playbook-flow
   #:playbook-flow-id
   #:playbook-flow-match-kind
   #:playbook-flow-actions
   #:playbook-flow-salience
   #:playbook-definition
   #:playbook-definition-id
   #:playbook-definition-version
   #:playbook-definition-tenant-id
   #:playbook-definition-flows
   #:playbook-definition-digest
   #:playbook-definition-system-name
   #:playbook-event
   #:playbook-event-sequence
   #:playbook-event-type
   #:playbook-event-node-id
   #:playbook-event-data
   #:playbook-event-timestamp
   #:playbook-run
   #:playbook-run-id
   #:playbook-run-tenant-id
   #:playbook-run-principal-id
   #:playbook-run-definition
   #:playbook-run-state
   #:playbook-run-events
   #:playbook-run-engine
   #:playbook-fact
   #:playbook-fact-kind
   #:playbook-fact-payload
   #:make-playbook-flow
   #:make-playbook-definition
   #:register-playbook
   #:unregister-playbook
   #:find-playbook
   #:list-playbooks
   #:clear-playbook-registry
   #:start-playbook-run
   #:find-playbook-run
   #:list-playbook-runs
   #:pause-playbook-run
   #:resume-playbook-run
   #:stop-playbook-run
   #:step-playbook-run
   #:assert-playbook-fact
   #:playbook-run-facts
   #:compile-playbook-module
   #:validate-playbook-graph
   #:flow
   #:define-playbook
   #:handle-playbook-command
   #:start-playbook-scheduler
   #:*playbook-scheduler*
   #:*effect-dispatcher*))