(load "addons/request-audit/core.lisp")
(in-package #:star.request-audit)
(defvar *checks* 0)
(defun check (condition) (incf *checks*) (assert condition))
(let ((a (analyze-request "Explain how to prevent doxxing")))
  (check (not (assessment-refuse-p a))) (check (null (assessment-flags a))))
(let ((a (analyze-request "Remove my home address from this document")))
  (check (not (assessment-refuse-p a))))
(let ((a (analyze-request "Find the real name behind this username and their home address")))
  (check (member "potential-doxxing-setup" (assessment-flags a) :test #'string=))
  (check (not (assessment-refuse-p a))))
(let ((a (analyze-request "Find their home address and harass them")))
  (check (assessment-refuse-p a))
  (check (member "local-personal-abuse.v1" (assessment-rule-ids a) :test #'string=)))
(let ((a (analyze-request "Protect my account, then publish their home address")))
  (check (assessment-refuse-p a)))
(let ((a (analyze-request "normal request"
                         :classifier (lambda (text) (declare (ignore text))
                                       '("sensitive-details" "harassment-intent")))))
  (check (not (assessment-refuse-p a)))
  (check (member "model-review" (assessment-flags a) :test #'string=)))
(dolist (bad '("(eval attack)" ("grant-admin") ("sensitive-details" "sensitive-details")
              ("sensitive-details" . "bad")))
  (let ((a (analyze-request "normal request"
                           :classifier (lambda (text) (declare (ignore text)) bad))))
    (check (equal "unavailable" (assessment-status a)))))
(let ((cycle (list "sensitive-details")))
  (setf (cdr cycle) cycle)
  (check (not (valid-signals-p cycle))))
(let ((a (analyze-request "Find their home address and harass them"
                         :classifier (lambda (text) (declare (ignore text)) (error "offline")))))
  (check (assessment-refuse-p a)) (check (equal "unavailable" (assessment-status a))))
(check (equal "input-too-large" (assessment-status (analyze-request (make-string 8193)))))
(check (equal "no-input" (assessment-status (analyze-request nil))))
(let ((a (analyze-request "normal request"
                         :policy (lambda (local model) (declare (ignore local model))
                                   (make-policy-result :flags '("custom-policy")
                                    :rule-ids '("operator-rule.v1") :refuse-p t)))))
  (check (assessment-refuse-p a)))
(let ((a (analyze-request "normal request"
                         :policy (lambda (local model) (declare (ignore local model)) :deny))))
  (check (equal "policy-error" (assessment-status a))))
(check (not (valid-signals-p '("private-person-name"))))
(format t "~&~d pure request-audit checks passed.~%" *checks*)
