;;; Contract fixtures: REAL policy.lisp/services.lisp with fake external ports.
;;; This is not a full ASDF/runtime, HTTP, cryptographic or transport test.
(require :asdf)
(defpackage #:jsown (:use #:cl) (:export #:new-js #:val #:val-safe #:keyp #:parse #:to-json))
(in-package #:jsown)
(defmacro new-js (&rest entries) `(list :obj ,@(loop for (k v) in entries collect `(cons ,k ,v))))
(defun val-safe (obj key) (and (consp obj) (cdr (assoc key (cdr obj) :test #'equal))))
(defun val (obj key) (val-safe obj key))
(defun keyp (obj key) (and (consp obj) (assoc key (cdr obj) :test #'equal)))
(defun parse (value) value)
(defun to-json (value) (declare (ignore value)) "{}")
(defpackage #:log (:use #:cl) (:shadow #:warn #:error) (:export #:info #:warn #:error))
(in-package #:log)
(defun info (&rest args) (declare (ignore args)))
(defun warn (&rest args) (declare (ignore args)))
(defun error (&rest args) (declare (ignore args)))
(defpackage #:star.ids (:use #:cl) (:export #:ulid))
(in-package #:star.ids)
(defun ulid () "01ARZ3NDEKTSV4RRFFQ69G5FAV")
(defpackage #:star (:use #:cl) (:export #:tenant-adaptation-for))
(in-package #:star)
(defun tenant-adaptation-for (dataset) (declare (ignore dataset)) "tenant-a")
(defpackage #:star.documents (:use #:cl) (:export #:document-value #:document-id #:document-dataset))
(in-package #:star.documents)
(defun document-value (obj key &optional fallback) (or (jsown:val-safe obj key) fallback))
(defun document-id (obj) (document-value obj "_id"))
(defun document-dataset (obj) (document-value obj "dataset"))
(defpackage #:star.auth
  (:use #:cl)
  (:export #:request-principal #:make-request-principal #:request-principal-id #:request-principal-type #:request-principal-scopes
           #:service-call-context #:service-call-context-principal-id #:service-call-context-principal-type #:service-call-context-scopes
           #:*request-security-context* #:request-security-context-correlation-id #:current-request-principal))
(in-package #:star.auth)
(defstruct request-principal id type scopes)
(defstruct service-call-context principal-id principal-type scopes)
(defvar *request-security-context* nil)
(defun request-security-context-correlation-id (context) (declare (ignore context)) nil)
(defun current-request-principal () nil)
(defun signal-lifecycle-error (&rest args) (declare (ignore args)) (error "Invalid scopes"))
(defpackage #:ironclad (:use #:cl) (:export #:make-hmac #:update-hmac #:hmac-digest #:byte-array-to-hex-string #:digest-sequence))
(defpackage #:babel (:use #:cl) (:export #:string-to-octets))
(defpackage #:star.audit (:use #:cl))
(in-package #:star.audit)
(defun safe-id (id &optional fallback) (if (and (stringp id) (plusp (length id))) id fallback))
(defun value (obj key) (jsown:val-safe obj key))
(defun decision-time (id) (declare (ignore id)) "2026-09-16T20:00:00.000000Z")
(in-package #:cl-user)
(load "source/authorization/package.lisp")
(load "source/authorization/policy.lisp")
(load "source/authorization/services.lisp")
(load "addons/request-audit/core.lisp")
(defvar *baseline* star.authorization:*policy-engine*)
(load "addons/request-audit/runtime.lisp")
(assert (eq *baseline* star.authorization:*policy-engine*))
(in-package #:star.request-audit)
(defvar *checks* 0)
(defun check (x) (incf *checks*) (assert x))
;; I/O is replaced at its port, not by replacing policy evaluation.
(defun request-event (engine request base result tenant proposed)
  (declare (ignore engine request base))
  (list :tenant tenant :status (assessment-status result) :proposed proposed))
(defparameter *admin* (star.auth:make-request-principal :id "operator" :type "user" :scopes '("admin")))
(defparameter *events* nil)
(defun recording-writer (event) (push event *events*))
(defun test-install (&rest options)
  (apply #'install :writers (list (cons "tenant-a" #'recording-writer))
         :hmac-key (make-array 32 :element-type '(unsigned-byte 8) :initial-element 1)
         :on-failure (lambda (code) (declare (ignore code))) options))
(defun target (intent)
  (jsown:new-js ("_id" "target-1") ("tenant_id" "tenant-a") ("dataset" "dataset-a")
                ("dtype" "target") ("data" (jsown:new-js ("objective" intent)))))
(defun request (text)
  (star.authorization:authorized-search-query text :principal *admin* :requested-tenant "tenant-a"))
(defun denial-code (thunk)
  (handler-case (progn (funcall thunk) nil)
    (star.authorization:authorization-error (c) (star.authorization:authorization-error-code c))))
(let ((undo (test-install)))
  (unwind-protect
       (progn
         (check (stringp (request "Find their home address and harass them")))
         (check (getf (first *events*) :proposed))
         (check (eq (document-intent (jsown:new-js ("dtype" "post") ("data" (jsown:new-js ("text" "harass them"))))) :absent)))
    (funcall undo)))
(check (not (typep star.authorization:*policy-engine* 'audit-policy-engine)))
(let ((undo (test-install :refusals-enabled t)))
  (unwind-protect
       (progn
         (check (equal "request_refused" (denial-code (lambda () (request "Publish their home address")))))
         (check (stringp (request "Remove my home address")))
         (let ((effects 0) (old (target "ordinary objective")))
           (check (equal "request_refused"
                         (denial-code
                          (lambda ()
                            (star.authorization:authorized-update-document
                             "target-1" (jsown:new-js ("data" (jsown:new-js ("objective" "Publish their home address"))))
                             (lambda (id) (declare (ignore id)) old)
                             (lambda (patch) (declare (ignore patch)) (incf effects)) :principal *admin*)))))
           (check (zerop effects)))
         (let ((effects 0))
           (check (equal "request_refused"
                         (denial-code (lambda ()
                           (star.authorization:authorize-bulk-documents!
                            (list (target "ordinary objective") (target "Publish their home address")) :principal *admin*)
                           (incf effects)))))
           (check (zerop effects)))
         (let ((before (length *events*)))
           (check (equal "access_denied" (denial-code (lambda ()
                            (star.authorization:authorized-search-query "Publish their home address")))))
           (check (= before (length *events*)))))
    (funcall undo)))
(dolist (enforce '(nil t))
  (let ((undo (test-install :refusals-enabled enforce :classifier (lambda (text) (declare (ignore text)) (error "offline")))))
    (unwind-protect
         (check (equal (if enforce "request_refused" nil) (denial-code (lambda () (request "ordinary query")))))
      (funcall undo))))
(let ((undo (test-install :refusals-enabled t
                         :classifier (lambda (text) (declare (ignore text)) '("sensitive-details" "harassment-intent")))))
  (unwind-protect (check (stringp (request "ordinary query"))) (funcall undo)))
(dolist (enforce '(nil t))
  (let ((undo (install :writers (list (cons "tenant-a" (lambda (event) (declare (ignore event)) (error "offline"))))
                       :hmac-key (make-array 32 :element-type '(unsigned-byte 8) :initial-element 1)
                       :refusals-enabled enforce :on-audit-error :deny
                       :on-failure (lambda (code) (declare (ignore code))))))
    (unwind-protect
         (check (equal (if enforce "request_audit_unavailable" nil)
                       (denial-code (lambda () (request "ordinary query")))))
      (funcall undo))))
(let* ((calls 0)
       (limited (star.auth:make-request-principal :id "limited" :type "user"
                  :scopes '("search:read" "tenant:tenant-a" "dataset:dataset-a")))
       (undo (test-install :classifier (lambda (text) (declare (ignore text)) (incf calls) nil))))
  (unwind-protect
       (progn
         (check (equal "access_denied" (denial-code (lambda ()
                  (star.authorization:authorized-search-query "ordinary query"
                   :principal limited :requested-tenant "tenant-b" :requested-dataset "dataset-a")))))
         (check (zerop calls)))
    (funcall undo)))
(check (handler-case (progn (test-install :refusals-enabled :yes) nil) (error () t)))
(check (not (typep star.authorization:*policy-engine* 'audit-policy-engine)))
(format t "~&~d request-audit REAL authorization/fake-port checks passed.~%" *checks*)
