(in-package :star.actors)

(defmacro with-json (jobject &body body)
  "Bind safe document readers for actor code.

The object is parsed once. Dtype resolution uses the versioned class registry and
never interns request-controlled text."
  (flet ((caller-symbol (name)
           (or (find-symbol name *package*)
               (intern name *package*))))
    (let ((document (gensym "DOCUMENT"))
          (val (caller-symbol "VAL"))
          (dataset (caller-symbol "DATASET"))
          (date-added (caller-symbol "DATE-ADDED"))
          (date-updated (caller-symbol "DATE-UPDATED"))
          (dtype (caller-symbol "DTYPE"))
          (parse-doc (caller-symbol "PARSE-DOC")))
      `(let ((,document (star.documents:parse-document-object ,jobject)))
         (flet ((,val (key &optional default)
                  (star.documents:document-field-value ,document key default))
                (,dataset ()
                  (star.documents:document-dataset ,document))
                (,date-added ()
                  (star.documents:document-date-added ,document))
                (,date-updated ()
                  (star.documents:document-date-updated ,document))
                (,dtype ()
                  (star.documents:document-dtype ,document))
                (,parse-doc ()
                  (star.documents:decode-document ,document)))
           ,@body)))))
