(uiop:define-package :star.documents
  (:nicknames :star.documents.v09)
  (:use :cl)
  (:export
   #:document-schema-profile
   #:v08-schema-profile
   #:v09-schema-profile
   #:schema-profile-version
   #:schema-profile-writable-p
   #:find-schema-profile
   #:schema-profile-for-document
   #:writable-schema-profile-for-document
   #:profile-data-slot-map
   #:normalize-document-for-index
   #:unsupported-document-schema
   #:read-only-document-schema
   #:document-class-registry
   #:class-registry-profile
   #:register-document-class
   #:registered-document-class
   #:registered-document-dtypes
   #:unknown-document-dtype
   #:unknown-document-dtype-value
   #:unknown-document-dtype-schema-version
   #:document-class-mismatch
   #:object-value
   #:parse-document-object
   #:document-field-value
   #:document-value
   #:document-data
   #:document-dataset
   #:document-dtype
   #:document-date-added
   #:document-date-updated
   #:document-transient-p
   #:decode-document
   #:ensure-v09-document
   #:v09-document-p
   #:v09-document-json
   #:v09-document-error))
