(uiop:define-package :starintel-gserver
  (:nicknames :star)
  (:use :cl)
  (:export
   #:*rabbit-password*
   #:*rabbit-user*
   #:*rabbit-port*
   #:*rabbit-address*
   #:*rabbit-max-retries*
   #:*rabbit-retry-base-delay-ms*
   #:*rabbit-retry-max-delay-ms*
   #:*rabbit-retry-jitter-ratio*
   #:*rabbit-quarantine-exchange*
   #:*rabbit-quarantine-queue*
   #:*http-scheme*
   #:*http-key-file*
   #:*http-cert-file*
   #:*http-api-base-path*
   #:*http-api-port*
   #:*http-api-address*
   #:*http-cors-allowed-origins*
   #:*http-cors-allowed-methods*
   #:*http-cors-allowed-headers*
   #:*couchdb-default-database*
   #:*couchdb-auth-database*
   #:*couchdb-host*
   #:*couchdb-port*
   #:*couchdb-user*
   #:*couchdb-password*
   #:*couchdb-scheme*
   #:*auth-mode*
   #:*auth-pepper*
   #:*auth-bootstrap-secret*
   #:*auth-dev-bypass*
   #:*auth-key-secret-bytes*
   #:*auth-salt-bytes*
   #:*auth-rotation-overlap-max-seconds*
   #:*auth-default-request-timeout-ms*
   #:*auth-max-request-timeout-ms*
   #:*auth-initial-username*
   #:*auth-initial-password*
   #:*auth-password-min-length*
   #:*auth-password-iterations*
   #:*auth-login-session-seconds*
   #:*auth-public-paths*
   #:main
   #:reload
   #:start-debugger
   #:*slynk-port*
   #:*actors-start-hook*
   #:*document-patterns*
   #:*ingest-workers*
   #:*couchdb-event-log-database*
   #:*couchdb-views*
   #:*star-server-version*
   #:ensure-init-file-exists
   #:load-init-file
   #:safe-load-init
   #:*bulk-max-documents*
   #:repl/main))

(uiop:define-package :star.databases.couchdb
  (:use :cl-couch :cl :star #:lparallel)
  (:export
   #:init-db
   #:init-views
   #:init-event-db
   #:get-targets*
   #:get-view-docs
   #:couchdb-view-request
   #:couchdb-view-request-method
   #:couchdb-view-request-uri
   #:couchdb-view-request-body
   #:view-query-error
   #:view-query-error-reason
   #:build-couchdb-view-request
   #:*couchdb-view-transport*
   #:query-view
   #:map-view-results
   #:get-neighbors
   #:search-fts
   #:sort-docs-by-date
   #:messages-by-user
   #:messages-by-platform
   #:messages-by-group
   #:social-posts-by-user
   #:social-posts-by-group
   #:by-channel
   #:export-by-dataset*
   #:count-by-dtype
   #:dataset-size
   #:total-documents-since
   #:orgs-by-country
   #:orgs-by-name
   #:persons-by-name
   #:persons-by-region
   #:relations-edges
   #:relations-incoming-count
   #:relations-outgoing-count
   #:targets-actor-counts
   #:targets-by-actor
   #:targets-target-count
   #:users-by-platform
   #:users-by-name
   #:as-json
   #:format-key
   #:from-json
   #:*couchdb-pool*
   #:groups
   #:lazy
   #:events-by-actor
   #:document-events
   #:target-events
   #:hosts-by-ip
   #:hosts-by-port
   #:hosts-by-service
   #:emails-by-email
   #:emails-by-domain
   #:emails-with-password
   #:domains-by-record
   #:domains-by-resolved-address
   #:networks-by-asn
   #:networks-by-org
   #:breaches-by-size
   #:urls-by-url
   #:urls-by-path
   #:urls-by-domain
   #:prepare-outbox-mutation
   #:persist-outbox-mutation
   #:process-outbox-mutation
   #:recover-outbox-documents
   #:document-outbox-entries
   #:find-outbox-entry
   #:outbox-entry-published-p
   #:outbox-entry-mutation-id
   #:outbox-entry-sequence
   #:mutation-conflict
   #:mutation-conflict-id
   #:mutation-conflict-document-id
   #:mutation-conflict-reason
   #:outbox-store-conflict
   #:missing-document-for-update
   #:couchdb-process-outbox-mutation
   #:couchdb-pending-outbox-documents
   #:recover-couchdb-outbox
   #:couchdb-save-quarantine-record
   #:couchdb-get-quarantine-record
   #:couchdb-list-quarantine-records
   #:update-quarantine-record
   #:mark-quarantine-replayed
   #:replay-quarantine-record
   #:target-acceptance-store-conflict
   #:couchdb-load-target-acceptance
   #:couchdb-save-target-acceptance
   #:couchdb-update-target-acceptance
   #:couchdb-persist-target-acceptance)
  (:documentation "CouchDB persistence and query helpers."))

(uiop:define-package :star.auth
  (:use :cl)
  (:export
   #:+api-key-prefix+
   #:authentication-error
   #:authentication-error-code
   #:authentication-error-message
   #:credential-lifecycle-error
   #:credential-lifecycle-error-code
   #:credential-lifecycle-error-message
   #:request-principal
   #:request-principal-id
   #:request-principal-type
   #:request-principal-scopes
   #:request-principal-credential-id
   #:request-security-context
   #:request-security-context-principal
   #:request-security-context-correlation-id
   #:request-security-context-deadline
   #:request-security-context-authenticated-at
   #:service-call-context
   #:service-call-context-principal-id
   #:service-call-context-principal-type
   #:service-call-context-credential-id
   #:service-call-context-scopes
   #:service-call-context-correlation-id
   #:service-call-context-deadline
   #:api-key-record
   #:api-key-record-id
   #:api-key-record-owner
   #:api-key-record-principal-type
   #:api-key-record-scopes
   #:api-key-record-status
   #:api-key-record-salt
   #:api-key-record-verifier
   #:api-key-record-created-at
   #:api-key-record-expires-at
   #:api-key-record-disabled-at
   #:api-key-record-revoked-at
   #:api-key-record-rotation-parent-id
   #:api-key-record-superseded-by
   #:api-key-record-overlap-expires-at
   #:api-key-record-revision
   #:credential-store
   #:memory-credential-store
   #:couchdb-credential-store
   #:make-memory-credential-store
   #:make-couchdb-credential-store
   #:credential-store-get
   #:credential-store-put
   #:credential-store-update
   #:credential-store-list
   #:credential-store-count
   #:*credential-store*
   #:*request-security-context*
   #:*auth-clock*
   #:*verifier-compare-function*
   #:auth-now
   #:constant-time-octets=
   #:constant-time-secret=
   #:parse-api-key
   #:bearer-token
   #:signal-authentication-failure
   #:authenticate-api-key
   #:authenticate-authorization-header
   #:current-request-principal
   #:current-principal-id
   #:current-service-call-context
   #:scope-granted-p
   #:administrator-principal-p
   #:create-api-key
   #:bootstrap-api-key
   #:rotate-api-key
   #:revoke-api-key
   #:disable-api-key
   #:api-key-metadata-json
   #:list-api-key-metadata
   #:user-record
   #:user-record-username
   #:user-record-principal-type
   #:user-record-scopes
   #:user-record-status
   #:user-record-created-at
   #:user-record-password-updated-at
   #:user-record-must-change-password
   #:user-store-get
   #:user-store-put
   #:user-store-update
   #:user-store-list
   #:user-store-count
   #:normalize-username
   #:create-user
   #:list-user-metadata
   #:user-metadata-json
   #:authenticate-user-password
   #:login-user
   #:change-user-password
   #:admin-set-user-password
   #:ensure-initial-user
   #:validate-auth-configuration
   #:initialize-auth-store))

(uiop:define-package :star.rabbit
  (:use :cl :star.consumers :sento.actor)
  (:documentation "RabbitMQ namespace")
  (:export
   #:with-rabbit-send
   #:with-rabbit-recv
   #:emit-document
   #:publish-raw-message
   #:+documents-exchange+
   #:+documents-exchange-type+
   #:+ingest-queue+
   #:+ingest-updates-queue+
   #:+updates-queue+
   #:+targets-queue+
   #:+ingest-key+
   #:+update-key+
   #:+targets-key+
   #:+ingest-fmt-key+
   #:+new-documents-key+
   #:+new-documents-fmt-key+
   #:+updated-documents-key+
   #:+updated-documents-fmt-key+
   #:+new-targets-key+
   #:+targets-fmt-key+
   #:+ingest-topic-key+
   #:+updates-topic-key+
   #:transient-p
   #:test-make-doc
   #:test-send
   #:decode-rabbit-document
   #:handle-document
   #:handle-update-document
   #:handle-target
   #:publish-outbox-event
   #:persist-quarantine-record
   #:inspect-quarantine
   #:replay-quarantined-message
   #:recover-pending-publications
   #:start-consumers))

(uiop:define-package :star.actors
  (:use :cl :star.databases.couchdb :sento.agent :sento.actor :sento.actor-system :sento.actor-context)
  (:documentation "Actor runtime namespace")
  (:export
   #:register-actor
   #:get-dest-actor
   #:*actor-index-agent*
   #:*targets*
   #:*target-timer*
   #:*couchdb-gets*
   #:*couchdb-inserts*
   #:*sys*
   #:start-actors
   #:start-target-timer
   #:start-target-actor
   #:define-actor
   #:with-json
   #:emit
   #:*producer-agent*
   #:*url-extractor*
   #:*pattern-agent*
   #:*pattern-actor*
   #:*wmn-relations-p*
   #:publish
   #:target-record
   #:target-record-id
   #:target-record-actor
   #:target-record-target
   #:target-record-delay
   #:target-record-recurring-p
   #:target-record-options
   #:target-record-document
   #:target-record-revision
   #:target-record-lease-owner
   #:target-record-lease-expires-at
   #:target-command
   #:target-command-record
   #:target-command-first-time-p
   #:target-command-recovered-p
   #:parse-target-record
   #:query-persisted-target-documents
   #:load-persisted-target-records
   #:submit-target
   #:sumbit-target
   #:recover-target-record
   #:recover-persisted-targets
   #:target-active-lease-p
   #:invalid-persisted-target
   #:invalid-target-document-id
   #:invalid-target-reason
   #:*recovered-target-fingerprints*
   #:target-destination-handle
   #:target-destination-handle-kind
   #:target-destination-handle-name
   #:target-destination-handle-component
   #:target-destination-handle-routing-key
   #:target-destination-handle-compatibility-routing-keys
   #:target-dispatch-envelope
   #:target-dispatch-envelope-record
   #:target-dispatch-envelope-destination
   #:target-dispatch-envelope-schedule-id
   #:target-dispatch-envelope-execution-id
   #:target-dispatch-envelope-attempt
   #:target-dispatch-envelope-trace-id
   #:target-dispatch-envelope-lease-id
   #:target-dispatch-envelope-fencing-token
   #:target-dispatch-envelope-deadline
   #:target-dispatch-outcome
   #:target-dispatch-outcome-status
   #:target-dispatch-outcome-reason
   #:target-dispatch-outcome-acceptance-id
   #:target-dispatch-outcome-envelope
   #:target-dispatch-outcome-retryable-p
   #:invalid-target-dispatch
   #:invalid-target-dispatch-reason
   #:target-ingress-overloaded
   #:target-ingress-overloaded-reason
   #:target-destination-unavailable
   #:target-destination-unavailable-reason
   #:canonical-target-routing-key
   #:compatibility-target-routing-keys
   #:resolve-target-destination
   #:validate-target-dispatch-record
   #:make-target-dispatch-envelope
   #:target-acceptance-id
   #:target-acceptance-document
   #:target-acceptance-equivalent-p
   #:dispatch-target-envelope-now
   #:register-target-schedule
   #:process-target-dispatch-envelope
   #:accept-target-record
   #:accept-target-delivery
   #:target-outcome-success-p
   #:make-remote-target-consumer
   #:*active-target-schedules*
   #:*target-max-delay-seconds*
   #:handle-event-message
   #:start-event-consumer
   #:log-actor-event
   #:*event-consumer*
   #:*actor-event-receiver*
   #:make-actor-event
   #:actor-event
   #:event-timestamp
   #:event-actor-name
   #:event-type
   #:event-details
   #:event-source-document
   #:event-id))

(uiop:define-package :starintel-gserver-http-api
  (:nicknames :star.frontends.http-api)
  (:use :cl :ningle :anypool :star.databases.couchdb :star)
  (:documentation "StarIntel HTTP API.")
  (:export
   #:*app*
   #:*default-headers*))
