(uiop:define-package :star.authorization
  (:use :cl)
  (:export
   #:+capabilities+
   #:+scope-prefixes+
   #:authorization-error
   #:authorization-error-code
   #:authorization-error-decision
   #:authorization-resource
   #:make-authorization-resource
   #:authorization-resource-tenant-id
   #:authorization-resource-dataset-id
   #:authorization-resource-actor-name
   #:authorization-resource-target-id
   #:authorization-resource-target-namespace
   #:authorization-resource-program-id
   #:authorization-resource-resource-id
   #:authorization-resource-dtype
   #:authorization-request
   #:authorization-request-principal
   #:authorization-request-action
   #:authorization-request-resource
   #:authorization-request-metadata
   #:authorization-request-quotas
   #:authorization-decision
   #:authorization-decision-id
   #:authorization-decision-allowed-p
   #:authorization-decision-reason
   #:authorization-decision-action
   #:authorization-decision-resource
   #:authorization-decision-principal-id
   #:trusted-authorization-context
   #:make-trusted-authorization-context
   #:trusted-authorization-context-id
   #:trusted-authorization-context-principal-type
   #:trusted-authorization-context-scopes
   #:policy-engine
   #:default-deny-policy-engine
   #:evaluate-authorization
   #:*policy-engine*
   #:*trusted-authorization-context*
   #:*current-authorization-decision*
   #:*authorization-audit-sink*
   #:validate-grant-scopes
   #:capability-granted-p
   #:scope-values
   #:resource-from-document
   #:authorize
   #:authorize!
   #:with-trusted-authorization-context
   #:decision-rabbit-headers
   #:authorization-audit-json
   #:authorize-document!
   #:authorized-fetch-document
   #:authorized-delete-document
   #:authorized-publish-document
   #:authorize-bulk-documents!
   #:authorized-target-documents
   #:authorized-search-query
   #:authorized-view-response
   #:principal-has-wildcard-dataset-p
   #:principal-has-capability-p
   #:+target-lease-service-result-codes+
   #:target-lease-service
   #:make-target-lease-service
   #:target-lease-service-store
   #:target-lease-service-runtime
   #:target-lease-service-service-instance-id
   #:target-lease-request-context
   #:make-target-lease-request-context
   #:target-lease-request-context-principal
   #:target-lease-request-context-tenant-id
   #:target-lease-request-context-dataset-id
   #:target-lease-request-context-program-id
   #:target-lease-request-context-target-namespace
   #:target-lease-request-context-target-id
   #:target-lease-request-context-actor-name
   #:target-lease-request-context-workflow-name
   #:target-lease-request-context-operation-class
   #:target-lease-request-context-request-id
   #:target-lease-request-context-deadline
   #:target-lease-request-context-ttl-ms
   #:target-lease-request-context-maximum-lifetime-ms
   #:target-lease-request-context-owner-client-id
   #:target-lease-request-context-execution-id
   #:target-lease-request-context-job-id
   #:target-lease-request-context-trace-id
   #:target-lease-request-context-metadata
   #:target-lease-service-result
   #:target-lease-service-result-code
   #:target-lease-service-result-lease
   #:target-lease-service-result-leases
   #:target-lease-service-result-retryable-p
   #:target-lease-service-result-detail
   #:target-lease-service-result-decision
   #:*target-lease-service*
   #:acquire-target-lease
   #:renew-target-lease
   #:release-target-lease
   #:get-target-lease
   #:list-target-leases
   #:revoke-target-lease
   #:current-target-lease-authority
   #:initialize-target-lease-service
   #:close-target-lease-service))
