(uiop:define-package :star.authorization
  (:use :cl)
  (:export
   #:+capabilities+
   #:+scope-prefixes+
   #:authorization-error
   #:authorization-error-code
   #:authorization-error-decision
   #:authorization-resource
   #:make-authorization-resource
   #:authorization-resource-tenant-id
   #:authorization-resource-dataset-id
   #:authorization-resource-actor-name
   #:authorization-resource-target-id
   #:authorization-resource-target-namespace
   #:authorization-resource-program-id
   #:authorization-resource-resource-id
   #:authorization-resource-dtype
   #:authorization-request
   #:authorization-request-principal
   #:authorization-request-action
   #:authorization-request-resource
   #:authorization-request-metadata
   #:authorization-request-quotas
   #:authorization-decision
   #:authorization-decision-id
   #:authorization-decision-allowed-p
   #:authorization-decision-reason
   #:authorization-decision-action
   #:authorization-decision-resource
   #:authorization-decision-principal-id
   #:trusted-authorization-context
   #:make-trusted-authorization-context
   #:trusted-authorization-context-id
   #:trusted-authorization-context-principal-type
   #:trusted-authorization-context-scopes
   #:policy-engine
   #:default-deny-policy-engine
   #:evaluate-authorization
   #:*policy-engine*
   #:*trusted-authorization-context*
   #:*current-authorization-decision*
   #:*authorization-audit-sink*
   #:validate-grant-scopes
   #:capability-granted-p
   #:scope-values
   #:resource-from-document
   #:authorize
   #:authorize!
   #:with-trusted-authorization-context
   #:decision-rabbit-headers
   #:authorization-audit-json
   #:authorize-document!
   #:authorized-fetch-document
   #:authorized-delete-document
   #:authorized-publish-document
   #:authorize-bulk-documents!
   #:authorized-target-documents
   #:authorized-search-query
   #:authorized-view-response
   #:principal-has-wildcard-dataset-p
   #:principal-has-capability-p))
